### ISSUE TITLE
Coupon Discounts is not applied when making a payment

### ISSUE THREAD

**Issue by Eumanuel** [imhinotori/WiseCP-MercadoPago#1]
When you make a payment that have a coupon added to it, it is like the coupon does not exist, the final value is the same with or without.

WISECP version: v2.3.2
OS: Ubuntu 20.04
Payment: PIX

**Comment by imhinotori** [comment]
Hi @Eumanuel,

I just pushed a fix, can you try it?

**Comment by Eumanuel** [comment]
Worked without any problems! Thank you =)
